name: Publish Local ETL
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: powershell

jobs:
  publish:
    runs-on: automate03-windows
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build appsettings file
        uses: cschleiden/replace-tokens@v1.3
        with:
          tokenPrefix: '$('
          tokenSuffix: ')'
          files: '**/appsettings.json'
        env:
          FILEPROCESSING_ROOT: ${{ vars.FILEPROCESSING_ROOT }}
          RABBITMQ_HOST: ${{ vars.RABBITMQ_HOST }}
          RABBITMQ_USER: ${{ vars.RABBITMQ_USER }}
          RABBITMQ_PASS: ${{ secrets.RABBITMQ_PASS }}
          RABBITMQ_EXCHANGE_UNANALYZED: ${{ vars.RABBITMQ_EXCHANGE_UNANALYZED }}
          RABBITMQ_ROUTE_UNANALYZED: ${{ vars.RABBITMQ_ROUTE_UNANALYZED }}

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.404'
          source-url: ${{ vars.NUGET_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN_GITEA }}

      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Publish app
        run: dotnet publish -c Release --no-build -p:PublishDir=${{ vars.PUBLISH_DIR }}
